"""
SmartCrop — Crop-specific Monitoring Thresholds (configuration)

This module holds the rule-based thresholds used by the monitoring engine.
It is separate from the monitoring logic on purpose: ranges and buffers can
be tuned here without touching the engine.

PROTOTYPE DISCLAIMER
--------------------
These values are PROTOTYPE/CONFIGURATION values. They are provided to make
the monitoring engine testable and extendable. They are NOT validated,
universally valid agricultural prescriptions.

Value provenance:
  * N, P, K, temperature, humidity, ph
        Derived from the project's own training dataset
        (Crop_recommendation_extended.csv): the recommended range is
        `mean +/- 1 std` of each crop's sample. This is the same data the
        existing Random Forest was trained on, so it is consistent with the
        existing project rather than an external claim.
  * soil_moisture
        NOT present in the training dataset. These are prototype placeholder
        ranges only (no dataset ground truth). Labeled `prototype: True`.
  * rainfall
        Intentionally NOT monitored. A single instantaneous rainfall reading
        does not represent a crop's water requirement, so the monitoring
        engine does not treat it as a thresholded parameter.
"""

# Recommended range [min, max] and warning `buffer` (absolute units).
#   NORMAL   : within [min, max]
#   WARNING  : outside [min, max] but within buffer of it
#   CRITICAL : farther than buffer from the range
CROP_THRESHOLDS = {
    "apple": {
        "N": {"min": 9, "max": 33, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 126, "max": 142, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 197, "max": 203, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 21.8, "max": 23.5, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 91, "max": 94, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.7, "max": 6.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 46, "max": 66, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "banana": {
        "N": {"min": 89, "max": 111, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 74, "max": 90, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 47, "max": 53, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 25.9, "max": 28.8, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 78, "max": 83, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.7, "max": 6.3, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 39, "max": 58, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "blackgram": {
        "N": {"min": 27, "max": 53, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 60, "max": 75, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 16, "max": 22, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 27.3, "max": 32.7, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 62, "max": 68, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.8, "max": 7.5, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 31, "max": 48, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "chickpea": {
        "N": {"min": 28, "max": 52, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 60, "max": 75, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 77, "max": 83, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 17.7, "max": 20.0, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 15, "max": 19, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.5, "max": 8.1, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 15, "max": 19, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "coconut": {
        "N": {"min": 10, "max": 34, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 9, "max": 25, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 28, "max": 34, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 26.0, "max": 28.8, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 92, "max": 98, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.7, "max": 6.3, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 46, "max": 69, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "coffee": {
        "N": {"min": 89, "max": 114, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 21, "max": 36, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 27, "max": 33, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 24.0, "max": 27.0, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 53, "max": 65, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.4, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 26, "max": 46, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "cotton": {
        "N": {"min": 106, "max": 129, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 39, "max": 54, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 16, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 22.9, "max": 25.1, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 77, "max": 83, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 7.5, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 38, "max": 58, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "grapes": {
        "N": {"min": 11, "max": 36, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 125, "max": 140, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 197, "max": 203, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 14.1, "max": 33.6, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 81, "max": 83, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.7, "max": 6.3, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 40, "max": 58, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "jute": {
        "N": {"min": 67, "max": 89, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 40, "max": 54, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 37, "max": 43, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 23.8, "max": 26.1, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 74, "max": 85, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 37, "max": 59, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "kidneybeans": {
        "N": {"min": 10, "max": 32, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 60, "max": 75, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 17, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 17.5, "max": 22.7, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 19, "max": 24, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.6, "max": 5.9, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 15, "max": 17, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "lentil": {
        "N": {"min": 7, "max": 31, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 61, "max": 76, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 16, "max": 22, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 21.2, "max": 27.8, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 62, "max": 68, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.4, "max": 7.5, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 31, "max": 48, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "maize": {
        "N": {"min": 66, "max": 90, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 40, "max": 56, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 17, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 19.7, "max": 25.1, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 60, "max": 71, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.8, "max": 6.7, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 30, "max": 50, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "mango": {
        "N": {"min": 8, "max": 32, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 20, "max": 35, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 27, "max": 33, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 28.6, "max": 33.9, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 47, "max": 53, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.1, "max": 6.5, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 24, "max": 37, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "mothbeans": {
        "N": {"min": 10, "max": 33, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 40, "max": 56, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 17, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 26.0, "max": 30.4, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 46, "max": 60, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.0, "max": 8.7, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 23, "max": 42, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "mungbean": {
        "N": {"min": 9, "max": 33, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 39, "max": 55, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 17, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 27.7, "max": 29.4, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 83, "max": 88, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.4, "max": 7.0, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 42, "max": 62, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "muskmelon": {
        "N": {"min": 88, "max": 112, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 11, "max": 25, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 47, "max": 53, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 27.8, "max": 29.5, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 91, "max": 94, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.1, "max": 6.6, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 46, "max": 66, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "mustard": {
        "N": {"min": 69, "max": 94, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 37, "max": 54, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 23, "max": 35, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 12.4, "max": 19.1, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 53, "max": 65, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 7.3, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 26, "max": 46, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "onion": {
        "N": {"min": 89, "max": 112, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 47, "max": 64, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 69, "max": 93, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 15.0, "max": 21.6, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 59, "max": 70, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.2, "max": 6.7, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 30, "max": 49, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "orange": {
        "N": {"min": 8, "max": 32, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 9, "max": 24, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 7, "max": 13, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 15.4, "max": 30.1, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 91, "max": 94, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.4, "max": 7.6, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 46, "max": 66, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "papaya": {
        "N": {"min": 38, "max": 62, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 52, "max": 66, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 47, "max": 53, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 27.5, "max": 40.0, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 91, "max": 94, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.6, "max": 6.9, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 46, "max": 66, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "pigeonpeas": {
        "N": {"min": 9, "max": 33, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 60, "max": 75, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 17, "max": 23, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 22.0, "max": 33.5, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 37, "max": 59, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.0, "max": 6.6, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 18, "max": 41, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "pomegranate": {
        "N": {"min": 6, "max": 31, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 11, "max": 26, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 37, "max": 43, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 19.6, "max": 24.0, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 87, "max": 93, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.9, "max": 6.9, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 44, "max": 65, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "rice": {
        "N": {"min": 68, "max": 92, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 40, "max": 55, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 37, "max": 43, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 21.7, "max": 25.7, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 81, "max": 84, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.7, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 40, "max": 59, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "sorghum": {
        "N": {"min": 69, "max": 92, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 36, "max": 54, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 27, "max": 45, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 26.7, "max": 32.6, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 46, "max": 60, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.0, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 23, "max": 42, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "sugarcane": {
        "N": {"min": 111, "max": 141, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 44, "max": 63, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 54, "max": 73, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 26.4, "max": 32.5, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 70, "max": 82, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 35, "max": 57, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "sunflower": {
        "N": {"min": 86, "max": 109, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 46, "max": 64, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 37, "max": 54, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 22.4, "max": 27.8, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 55, "max": 66, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.4, "max": 7.2, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 28, "max": 46, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "tobacco": {
        "N": {"min": 49, "max": 70, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 35, "max": 53, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 89, "max": 113, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 22.1, "max": 28.2, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 63, "max": 71, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 5.8, "max": 6.7, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 32, "max": 50, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "tomato": {
        "N": {"min": 88, "max": 111, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 57, "max": 74, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 87, "max": 110, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 19.7, "max": 25.0, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 59, "max": 70, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 6.8, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 30, "max": 49, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "watermelon": {
        "N": {"min": 87, "max": 112, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 9, "max": 25, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 47, "max": 53, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 24.7, "max": 26.4, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 82, "max": 88, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.2, "max": 6.8, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 41, "max": 62, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
    "wheat": {
        "N": {"min": 107, "max": 131, "buffer": 12,
            "unit": "kg/ha", "label": "Nitrogen",
            "fertilizer": "nitrogen-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "P": {"min": 48, "max": 74, "buffer": 8,
            "unit": "kg/ha", "label": "Phosphorus",
            "fertilizer": "phosphorus-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "K": {"min": 35, "max": 54, "buffer": 5,
            "unit": "kg/ha", "label": "Potassium",
            "fertilizer": "potassium-based",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "temperature": {"min": 14.4, "max": 20.2, "buffer": 3.0,
            "unit": "degC", "label": "Air temperature",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "humidity": {"min": 54, "max": 66, "buffer": 7,
            "unit": "%", "label": "Relative humidity",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "ph": {"min": 6.3, "max": 7.3, "buffer": 0.4,
            "unit": "pH", "label": "Soil pH",
            "derived_from": "training dataset (mean +/- 1 std)"},
        "soil_moisture": {"min": 27, "max": 46, "buffer": 10,
            "unit": "%", "label": "Soil moisture",
            "prototype": True,
            "derived_from": "prototype placeholder - not present in dataset"},
    },
}

# Extending to all 30 crops: add a key per crop name (the same names the
# model's label encoder uses, e.g. 'banana', 'cotton', 'tomato', ...) with the
# parameter structure shown above.

# List of all crop names currently supported by the monitoring engine.
MONITORED_CROPS = list(CROP_THRESHOLDS.keys())

# ── Monitoring engine configuration ──────────────────────────────────────
# All thresholds below are configuration values (no magic numbers in the
# engine code).
MONITOR_CONFIG = {
    # Historical analysis window (hours).
    "window_hours": 72,

    # Minimum number of historical readings required before a condition can
    # be declared persistent. Fewer readings = "insufficient_history".
    "min_readings_for_persistence": 3,

    # Percentage of readings outside the recommended range that decide the
    # persistence classification:
    #   abnormal_pct <  monitor_ceiling                    -> monitor
    #   monitor_ceiling >= abnormal_pct >= warning_ceiling -> warning   (keep config crosses boundaries explicit)
    #   abnormal_pct  >  abnormal_persistent_floor         -> persistent
    # Implemented as: <40 monitor, 40-70 warning, >70 persistent.
    "abnormal_monitor_ceiling": 40,
    "abnormal_warning_ceiling": 70,
    "abnormal_persistent_floor": 70,

    # Trend: if |total change across history| <= sensitivity * range_width
    # then the parameter is considered "stable".
    "trend_sensitivity": 0.10,

    # Transparent health-score deduction weights.
    # Label: "SmartCrop Monitoring Health Score" (prototype decision-support
    # metric, NOT a validated crop-health index).
    "health_score_label": "SmartCrop Monitoring Health Score",
    "health_score_note": (
        "Prototype decision-support metric. Starts at 100 and deducts "
        "points for abnormal readings, persistent issues and aggravating "
        "trends. Not a scientifically validated crop-health index."
    ),
    "scoring": {
        "base": 100,
        "warning": 8,
        "critical": 15,
        "persistent": 10,
        "aggravating_trend": 5,
    },

    "note": (
        "PROTOTYPE configuration. Thresholds derived from the project's "
        "training dataset (mean +/- 1 std) or marked as prototype "
        "placeholders (soil_moisture). Not validated agronomic prescriptions."
    ),
}


def available_crops():
    """Return the list of crops the monitoring engine currently supports."""
    return list(CROP_THRESHOLDS.keys())


def get_thresholds(crop):
    """Return the threshold config dict for a crop.

    Raises KeyError with a helpful message if the crop is not configured.
    """
    key = str(crop).strip().lower()
    if key not in CROP_THRESHOLDS:
        raise KeyError(
            f"Unknown crop '{crop}'. Supported crops for monitoring: "
            f"{sorted(CROP_THRESHOLDS.keys())}"
        )
    return CROP_THRESHOLDS[key]


def config_for_crop(crop, overrides=None):
    """Return the effective MONITOR_CONFIG (optionally overridden)."""
    get_thresholds(crop)  # validate crop exists
    config = dict(MONITOR_CONFIG)
    config["scoring"] = dict(MONITOR_CONFIG["scoring"])
    if overrides:
        if "scoring" in overrides and isinstance(overrides["scoring"], dict):
            config["scoring"].update(overrides["scoring"])
        config.update({k: v for k, v in overrides.items() if k != "scoring"})
    return config