// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgHJCJAJ8awxhdHwCn9kj7SKvr8jz7O8',
    appId: '1:1083437709603:web:af6bc40d94a5aeb292f496',
    messagingSenderId: '1083437709603',
    projectId: 'smart-crop-ddf69',
    authDomain: 'smart-crop-ddf69.firebaseapp.com',
    storageBucket: 'smart-crop-ddf69.firebasestorage.app',
    measurementId: 'G-JD5ZHFL60L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChsHBhrYf8l6u6VCQ-YUF8H7FQ1vexI6M',
    appId: '1:1083437709603:android:be6fa7e6bb055b4992f496',
    messagingSenderId: '1083437709603',
    projectId: 'smart-crop-ddf69',
    storageBucket: 'smart-crop-ddf69.firebasestorage.app',
  );
}
